/**
 * File Scanner — dashboard to view scan results from the local PDF scanner script.
 * Reads from /data/output.json (generated by scripts/scanWithOCR-local.ts).
 * Two views: Table view (filterable flat list) and Folder view (date → property folder → files).
 */

import { useState, useCallback } from 'react';
import { useQuery } from '@tanstack/react-query';
import {
  ArrowPathIcon,
  CloudArrowUpIcon,
  TableCellsIcon,
  FolderOpenIcon,
} from '@heroicons/react/24/outline';
import { clsx } from 'clsx';
import { ScannerStats } from '../components/scanner/ScannerStats';
import { FileTable } from '../components/scanner/FileTable';
import { FileDetailPanel } from '../components/scanner/FileDetailPanel';
import { PropertyFolderBrowser } from '../components/scanner/PropertyFolderBrowser';
import { ScanControls } from '../components/scanner/ScanControls';
import type { ScanSummary, FlatResult } from '../components/scanner/types';

type MainView = 'table' | 'folders';

export function ScannerPage() {
  const [mainView, setMainView] = useState<MainView>('folders');
  const [selectedFile, setSelectedFile] = useState<FlatResult | null>(null);
  const [selectedDate, setSelectedDate] = useState('');

  // Load the scan output JSON from public/data or served statically
  const { data: summary, isLoading, error, refetch } = useQuery<ScanSummary>({
    queryKey: ['scan-results'],
    queryFn: async () => {
      const res = await fetch('/data/output.json');
      if (!res.ok) throw new Error('No scan results found. Run the scanner script first.');
      return res.json() as Promise<ScanSummary>;
    },
    staleTime: 30_000,
    retry: false,
  });

  const handleSelectFile = useCallback((file: FlatResult) => {
    setSelectedFile((prev) => prev?.relativePath === file.relativePath ? null : file);
  }, []);

  // All hooks must be called before any early returns
  const handleScanComplete = useCallback(() => {
    refetch();
  }, [refetch]);

  const allResults = summary?.results ?? [];

  // Loading skeleton
  if (isLoading) {
    return (
      <div className="p-6 max-w-[1400px] mx-auto">
        <div className="h-6 w-48 bg-neutral-200 rounded animate-pulse mb-6" />
        <div className="grid grid-cols-6 gap-3 mb-6">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="card h-20 animate-pulse bg-neutral-100" />
          ))}
        </div>
        <div className="card h-96 animate-pulse bg-neutral-100" />
      </div>
    );
  }

  // Empty/error state — show scan controls prominently
  if (error || !summary) {
    return (
      <div className="p-6 max-w-[1400px] mx-auto">
        <h1 className="text-xl font-bold text-gray-900 mb-6">File Scanner</h1>
        <ScanControls onScanComplete={handleScanComplete} />
        <div className="card flex flex-col items-center justify-center py-12 mt-4">
          <CloudArrowUpIcon className="w-12 h-12 text-neutral-300 mb-3" />
          <p className="text-sm font-semibold text-neutral-700 mb-1">No scan results yet</p>
          <p className="text-xs text-neutral-400 mb-4 max-w-md text-center">
            Enter a folder path above and click Start Scan, or run the scanner from the terminal.
          </p>
          <button onClick={() => refetch()} className="btn-secondary">
            <ArrowPathIcon className="w-4 h-4" />
            Refresh Results
          </button>
        </div>
      </div>
    );
  }


  const scannedDate = new Date(summary.scannedAt).toLocaleString();

  return (
    <div className="p-6 max-w-[1600px] mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-5">
        <div>
          <h1 className="text-xl font-bold text-gray-900">File Scanner</h1>
          <p className="text-xs text-neutral-400 mt-0.5">
            Scanned {scannedDate} &middot; {summary.scanRoot.split('/').slice(-2).join('/')}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {/* View toggle */}
          <div className="flex rounded-md border border-neutral-200 overflow-hidden">
            <button
              onClick={() => { setMainView('folders'); setSelectedFile(null); }}
              className={clsx(
                'flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium transition-colors',
                mainView === 'folders'
                  ? 'bg-brand-50 text-brand-700'
                  : 'bg-white text-neutral-500 hover:bg-neutral-50',
              )}
            >
              <FolderOpenIcon className="w-3.5 h-3.5" />
              Folders
            </button>
            <button
              onClick={() => { setMainView('table'); setSelectedFile(null); }}
              className={clsx(
                'flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium transition-colors border-l border-neutral-200',
                mainView === 'table'
                  ? 'bg-brand-50 text-brand-700'
                  : 'bg-white text-neutral-500 hover:bg-neutral-50',
              )}
            >
              <TableCellsIcon className="w-3.5 h-3.5" />
              Table
            </button>
          </div>

          {/* Date filter — only for Folders view */}
          {mainView === 'folders' && summary.allDates.length > 0 && (
            <select
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="btn-secondary !py-1.5 text-xs"
            >
              <option value="">All dates ({summary.allDates.length})</option>
              {summary.allDates.map((d) => (
                <option key={d} value={d}>{d}</option>
              ))}
            </select>
          )}

          <button onClick={() => refetch()} className="btn-secondary !py-1.5">
            <ArrowPathIcon className="w-3.5 h-3.5" />
            <span className="text-xs">Refresh</span>
          </button>
        </div>
      </div>

      {/* Scan controls — collapsible */}
      <div className="mb-4">
        <ScanControls onScanComplete={handleScanComplete} />
      </div>

      {/* Stats strip */}
      <ScannerStats summary={summary} />

      {/* ── Folder View ─────────────────────────────────────────────────────── */}
      {mainView === 'folders' && (
        <div className="mt-5">
          <PropertyFolderBrowser
            summary={summary}
            selectedDate={selectedDate}
          />
        </div>
      )}

      {/* ── Table View ──────────────────────────────────────────────────────── */}
      {mainView === 'table' && (
        <div className="grid grid-cols-12 gap-4 mt-5">
          {/* File table — filters are built into the table toolbar */}
          <div className={clsx(selectedFile ? 'col-span-8' : 'col-span-12')}>
            <FileTable
              results={allResults}
              onSelectFile={handleSelectFile}
              selectedFile={selectedFile}
            />
          </div>

          {/* Right: detail panel */}
          {selectedFile && (
            <div className="col-span-4 card overflow-hidden sticky top-6 self-start max-h-[calc(100vh-120px)]">
              <FileDetailPanel
                file={selectedFile}
                onClose={() => setSelectedFile(null)}
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
